
hindi_movies = [
    'Lagaan',
    'Rang de basanti',
    'Gangs of Wasseypur',
    'Swades',
    'Mughal e azam',
    'Taare Zameen par',
    'A Wednesday',
    'Dangal',
    'Udaan',
    'Bhaag Milkha Bhaag',
    'Haider',
    'Shahid',
    'Dil Chahta hai',
    'Queen',
    'Drishyam',
    'Guru',
    'My name is Khan',
    'Kahaani',
    'Salaam Bombay',
    'Black',
    'Omkara',
    'Dev D',
    'Mother India',
    'Kaagaz ke Phool',
    'Roja',
    'Jab we met',
    'Airlift',
    'Jo Jeeta Wohi Sikhandar',
    'Mumbai meri jaan',
    'Oye lucky lucky oye',
    'Kal ho na ho',
    'Rock on',
    'Dilwale Dulhaniya le jayenge',
    'Baajirao Mastani',
    'Satya',
    'Dil se',
    'Vicky Donor',
    'Pink',
    'Lootera',
    'Neerja',
    'The lunchbox',
    'Dear Zindagi',
    'Udta Punjab',
    'Nil battey sannata',
    'Talvar'
    ]

english_movies = [
    'The Shawshank Redemption',
    'Schindlers list',
    'The Godfather',
    'Scarface',
    'The bucket list',
    'The terminal',
    'Catch me if you can',
    'As good as it gets',
    'The departed',
    'Cast away',
    'Good will hunting',
    'The Blind side',
    'Scent of a woman',
    'Titanic',
    'Perfume',
    'The pursuit of happiness',
    'Gladiator',
    'The pianist',
    'The silence of the lambs',
    'Pride and prejudice',
    'The matrix',
    'The sixth sense',
    'When Harry met Sally',
    'Love actually',
    'Thee Namesake',
    'Troy',
    'The Exorcist',
    'The Prestige',
    'Once upon a time in America',
    'The kings speech',
    'Life of pi',
    'Avatar',
    'Harry Potter',
    'The Lord of the rings',
    'Victoria',
    'La La Land',
    'If only',
    'A walk to remember',
    'The notebook',
    'What happens in Vegas',
    ]
