
movies = [
    'Lagaan',
    'Rang de basanti',
    'Gangs of Wasseypur',
    'Swades',
    'Mughal e azam',
    'Taare Zameen par',
    'A Wednesday',
    'Dangal',
    'Udaan',
    'Bhaag Milkha Bhaag',
    'Haider',
    'Shahid',
    'Dil Chahta hai',
    'Queen',
    'Drishyam',
    'Guru',
    'My name is Khan',
    'Kahaani',
    'Salaam Bombay',
    'Black',
    'Omkara',
    'Dev D',
    'Mother India',
    'Kaagaz ke Phool',
    'Roja',
    'Jab we met',
    'Airlift',
    'Jo Jeeta Wohi Sikhandar',
    'Mumbai meri jaan',
    'Oye lucky lucky oye',
    'Kal ho na ho',
    'Rock on',
    'Dilwale Dulhaniya le jayenge',
    'Baajirao Mastani',
    'Satya',
    'Dil se',
    'Vicky Donor',
    'Pink',
    'Lootera',
    'Neerja',
    'The lunchbox',
    'Dear Zindagi',
    'Udta Punjab',
    'Nil battey sannata',
    'Talvar'
    ]